### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Missing key ckpt

### ISSUE THREAD

**Issue by toyxyz** [maxin-cn/Cinemo#11]
Thanks for the great work! 

When I ran video_editing.sh, I got the following error. 

I checked the sample.yaml and there is no ckpt part. 

Am I missing something? The gardio app works fine.

```
(cinemo) C:\Users\toyxy\Cinemo>bash pipelines/video_editing.sh
C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\diffusers\models\modeling_utils.py:109: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location="cpu")
Traceback (most recent call last):
  File "C:\Users\toyxy\Cinemo\pipelines\video_editting.py", line 198, in <module>
    main(OmegaConf.load(args.config))
  File "C:\Users\toyxy\Cinemo\pipelines\video_editting.py", line 87, in main
    state_dict = find_model(args.ckpt)
                            ^^^^^^^^^
  File "C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\omegaconf\dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "C:\Users\toyxy\ANACON~1\envs\cinemo\Lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key ckpt
    full_key: ckpt
    object_type=dict
```

**Comment by maxin-cn** [comment]
Hi, thanks for your interest. I have fixed this bug. the parameter `ckpt` will not be used. You can follow this to change your code:
https://github.com/maxin-cn/Cinemo/blob/d0e99565dc60084f6afc6c8767463ffc5337b082/pipelines/video_editing.py#L90
