### ISSUE TITLE
Problem loading models

### ISSUE THREAD

**Issue by freeexit2002** [maxin-cn/Cinemo#6]
This is the problem. Thanks in advance

cinemo) C:\AI\Cinemo>python app.py
C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\diffusers\models\modeling_utils.py:109: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location="cpu")
Will cache examples in 'C:\AI\Cinemo\gradio_cached_examples\40' directory at first use.

ERROR:    [Errno 11002] getaddrinfo failed
Exception in thread Thread-3 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpcore\_sync\connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: _ssl.c:983: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\analytics.py", line 70, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\analytics.py", line 131, in get_local_ip_address
    ip_address = httpx.get(
                 ^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_api.py", line 198, in get
    return request(
           ^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:983: The handshake operation timed out
ERROR:    [Errno 11002] getaddrinfo failed
Traceback (most recent call last):
  File "C:\AI\Cinemo\app.py", line 309, in <module>
    demo.launch(debug=False, share=True, server_name="8.8.8.8")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\blocks.py", line 2353, in launch
    ) = http_server.start_server(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\http_server.py", line 154, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 7860-7959. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`. I tried different ports but received the same errors.

**Comment by maxin-cn** [comment]
Thanks for your reminder. I have fixed this bug. You can use the latest code.
