### ISSUE TITLE
TypeError: PyAVPlugin.write() got an unexpected keyword argument 'quality'

### ISSUE THREAD

**Issue by freeexit2002** [maxin-cn/Cinemo#7]
C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\diffusers\models\attention_processor.py:1231: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  hidden_states = F.scaled_dot_product_attention(
Using DCT!
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [01:19<00:00,  1.59s/it]
Traceback (most recent call last):
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\AI\Cinemo\app.py", line 203, in gen_video
    imageio.mimwrite(save_path, videos[0], fps=8, quality=7)
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\imageio\v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PyAVPlugin.write() got an unexpected keyword argument 'quality'
C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use 

maybe you could use opencv library

`force_download=True`.
  warnings.warn(
Using DCT!
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [24:16<00:00, 29.13s/it]
Traceback (most recent call last):
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\AI\Cinemo\app.py", line 203, in gen_video
    imageio.mimwrite(save_path, videos[0], fps=8, quality=7)
  File "C:\Users\mastoras\.conda\envs\cinemo\Lib\site-packages\imageio\v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PyAVPlugin.write() got an unexpected keyword argument 'quality'

**Comment by maxin-cn** [comment]
It seems that some packages are missing. Please follow this [requirement](https://huggingface.co/spaces/maxin-cn/Cinemo/blob/main/requirements.txt) to install your environment.
